/* =========================================================
   Lhawta — Données produits
   Données fictives. Remplace les images par tes vraies photos
   dans /images/produits/ une fois tes shots prêts.
   ========================================================= */

const PRODUCTS = [
  {
    id: 1,
    name: "Chemise vintage rayée",
    reference: "LHW-001",
    category: "chemise",
    size: "M",
    price: 120,
    condition: "Très bon état",
    status: "Disponible",
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&h=750&fit=crop",
    styleTags: ["vintage", "minimal"],
    occasionTags: ["quotidien", "école", "sortie"],
    description: "Chemise légère, coupe clean, parfaite pour un look vintage."
  },
  {
    id: 2,
    name: "Blouson noir oversize",
    reference: "LHW-002",
    category: "blouson",
    size: "L",
    price: 280,
    condition: "Comme neuf",
    status: "Disponible",
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=750&fit=crop",
    styleTags: ["streetwear", "oversize"],
    occasionTags: ["quotidien", "sortie", "événement"],
    description: "Blouson noir coupe oversize, idéal pour un look streetwear."
  },
  {
    id: 3,
    name: "T-shirt baseball",
    reference: "LHW-003",
    category: "t-shirt",
    size: "M",
    price: 90,
    condition: "Très bon état",
    status: "Disponible",
    image: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=600&h=750&fit=crop",
    styleTags: ["vintage", "streetwear"],
    occasionTags: ["quotidien", "école"],
    description: "T-shirt baseball manches contrastées, esprit vintage US."
  },
  {
    id: 4,
    name: "Chemise beige casual",
    reference: "LHW-004",
    category: "chemise",
    size: "L",
    price: 150,
    condition: "Neuf",
    status: "Vendu",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&h=750&fit=crop",
    styleTags: ["chic casual", "minimal"],
    occasionTags: ["travail", "sortie", "événement"],
    description: "Chemise beige neuve, coupe régulière, indispensable du dressing."
  },
  {
    id: 5,
    name: "Pull vintage vert",
    reference: "LHW-005",
    category: "pull",
    size: "M",
    price: 180,
    condition: "Bon état",
    status: "Disponible",
    image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&h=750&fit=crop",
    styleTags: ["vintage", "chic casual"],
    occasionTags: ["quotidien", "école", "travail"],
    description: "Pull vert olive, maille épaisse, vibe 90's authentique."
  },
  {
    id: 6,
    name: "Pantalon cargo",
    reference: "LHW-006",
    category: "pantalon",
    size: "L",
    price: 220,
    condition: "Très bon état",
    status: "Disponible",
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&h=750&fit=crop",
    styleTags: ["streetwear", "oversize"],
    occasionTags: ["quotidien", "sortie"],
    description: "Cargo multipoches, coupe ample, parfait pour le quotidien."
  },
  {
    id: 7,
    name: "Veste denim",
    reference: "LHW-007",
    category: "veste",
    size: "M",
    price: 250,
    condition: "Très bon état",
    status: "Disponible",
    image: "https://images.unsplash.com/photo-1543076447-215ad9ba6923?w=600&h=750&fit=crop",
    styleTags: ["vintage", "streetwear"],
    occasionTags: ["quotidien", "sortie", "école"],
    description: "Trucker en denim brut, le classique intemporel."
  },
  {
    id: 8,
    name: "T-shirt blanc minimal",
    reference: "LHW-008",
    category: "t-shirt",
    size: "S",
    price: 60,
    condition: "Neuf",
    status: "Disponible",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=750&fit=crop",
    styleTags: ["minimal", "chic casual"],
    occasionTags: ["quotidien", "travail", "école"],
    description: "T-shirt blanc, coton épais, base parfaite de tout look."
  },
  {
    id: 9,
    name: "Blouson coupe-vent",
    reference: "LHW-009",
    category: "blouson",
    size: "XL",
    price: 200,
    condition: "Bon état",
    status: "Vendu",
    image: "https://images.unsplash.com/photo-1559563458-527698bf5295?w=600&h=750&fit=crop",
    styleTags: ["streetwear", "oversize"],
    occasionTags: ["quotidien", "sortie"],
    description: "Coupe-vent léger, parfait pour la mi-saison."
  },
  {
    id: 10,
    name: "Chemise premium",
    reference: "LHW-010",
    category: "chemise",
    size: "L",
    price: 300,
    condition: "Neuf",
    status: "Disponible",
    image: "https://images.unsplash.com/photo-1602810316693-3667c854239a?w=600&h=750&fit=crop",
    styleTags: ["chic casual", "minimal"],
    occasionTags: ["travail", "événement", "sortie"],
    description: "Chemise premium, tissu noble, finitions impeccables."
  },
  {
    id: 11,
    name: "Pull oversize gris",
    reference: "LHW-011",
    category: "pull",
    size: "XL",
    price: 170,
    condition: "Très bon état",
    status: "Disponible",
    image: "https://images.unsplash.com/photo-1599658880436-c61792e70672?w=600&h=750&fit=crop",
    styleTags: ["oversize", "streetwear"],
    occasionTags: ["quotidien", "école"],
    description: "Pull oversize confort maximal, idéal pour les jours froids."
  },
  {
    id: 12,
    name: "Pantalon chino beige",
    reference: "LHW-012",
    category: "pantalon",
    size: "M",
    price: 160,
    condition: "Neuf",
    status: "Disponible",
    image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&h=750&fit=crop",
    styleTags: ["chic casual", "minimal"],
    occasionTags: ["travail", "événement", "école"],
    description: "Chino beige, coupe slim, pour un look propre et passe-partout."
  }
];
